--- # Ansible Playbook to configure static webserver and use it to create new template
- hosts: aws
  connection: ssh
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks: 
  - name: Connect remote host, execute yum updates
    apt:
      update_cache: yes
  - name: Install the httpd server
    apt:
      name: apache2
      update_cache: yes
      state: latest
  - name: Deploy the static website
    copy: 
      src=files/index.html
      dest=/var/www/html/index.html
      owner=root
      group=root
      mode=0655
      backup=yes
  - name: Restart the HTTPD service
    service:
      name: apache2 
      state: restarted
  - name: Wait for the HTTPD port 80 to be listening 
    wait_for:
      host=ec2-34-203-197-107.compute-1.amazonaws.com 
      port=80
      delay=20
  - name: Install WGET to test the site 
    apt: 
      name: wget
      state: latest
  - name: Test the site
    shell: /usr/bin/wget http://localhost
    register: site_result
  - name: Display the site output results
    debug: var=site_result

- hosts: localhost
  connection: local 
  remote_user: projectx
  become: yes
  gather_facts: no 
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Take a snapshot backup of the website directory
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0160b8c8feee81fb6
      device_name: /dev/sdb
      description: Initial Playbook Static Site Deployement Backup
      wait: no 
    register: snapshot_results
  - name: Display the snapshot results
    debug: var=snapshot_results
  - name: Create new AMI Template from our instance 
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key}}"
      region: "{{ aws_region }}"
      instance_id: i-0160b8c8feee81fb6
      wait: no 
      name: myansible_amitemplate
      tags: 
        Name: MyAnsible_AMITemplate
    register: ami_results
  - name: Display the AMI creation results
    debug: var=ami_results
